import { ControlItem } from "../../frontend";
interface Catalogo65 {
	items: ControlItem[];
}

/*
* Catálogo No. 65:
* Campo:
* ext: ...
* Descripción:
* Código de unidades de medida (para uso solo para la GRE en DAM o DS)
* Catálogo:
* SUNAT
* */
export const catalogo65: Catalogo65 = {
	items: [
		{ value: 1, label:"DOCENA POR 10**6" },
		{ value: 2, label:"DOCENA" },
		{ value: 3, label:"PAR" },
		{ value: 4, label:"PAR POR 10**6" },
		{ value: 5, label:"AMPOLLA" },
		{ value: 6, label:"BALDE" },
		{ value: 7, label:"BIDONES" },
		{ value: 8, label:"BOLSA" },
		{ value: 9, label:"BOBINAS" },
		{ value: 10, label:"BOTELLAS" },
		{ value: 11, label:"BARRILES" },
		{ value: 12, label:"CAJA" },
		{ value: 13, label:"CILINDRO" },
		{ value: 14, label:"CENTIMETRO LINEAL" },
		{ value: 15, label:"CENTIMETRO CUADRADO" },
		{ value: 16, label:"CENTIMETRO CUBICO" },
		{ value: 17, label:"CONOS" },
		{ value: 18, label:"CARTONES" },
		{ value: 19, label:"FARDO" },
		{ value: 20, label:"FRASCOS" },
		{ value: 21, label:"US GALON (3,7843 L)" },
		{ value: 22, label:"GALON INGLES (4,545956L)" },
		{ value: 23, label:"GRAMO" },
		{ value: 24, label:"GRUESA" },
		{ value: 25, label:"HECTOLITRO" },
		{ value: 26, label:"HOJA" },
		{ value: 27, label:"JUEGO" },
		{ value: 28, label:"KILOGRAMO" },
		{ value: 29, label:"KILOGRAMO POR 10**3 (TM)" },
		{ value: 30, label:"KILOGRAMO POR 10**6" },
		{ value: 31, label:"KILOGRAMO INGREDIENTE ACTIVO" },
		{ value: 32, label:"QUILATE" },
		{ value: 33, label:"QUILATE 10**6" },
		{ value: 34, label:"KIT" },
		{ value: 35, label:"KILOS X 10 EXP - 6 (MG)" },
		{ value: 36, label:"KILOS X 10 EXP -9" },
		{ value: 37, label:"KILOMETRO" },
		{ value: 38, label:"KILOVATIO HORA POR 10**3 (1000KWH)" },
		{ value: 39, label:"KILOVATIO HORA POR 10**6" },
		{ value: 40, label:"KILOVATIO HORA" },
		{ value: 41, label:"LITRO" },
		{ value: 42, label:"LITRO POR 10**6" },
		{ value: 43, label:"LATAS" },
		{ value: 44, label:"LIBRAS" },
		{ value: 45, label:"METRO" },
		{ value: 46, label:"METRO POR 10**6" },
		{ value: 47, label:"METRO CUADRADO" },
		{ value: 48, label:"METRO CUADRADO POR 10**6" },
		{ value: 49, label:"METRO CUBICO" },
		{ value: 50, label:"METRO CUBICO POR 10**6" },
		{ value: 51, label:"MILIGRAMO ACTIVO" },
		{ value: 52, label:"MILIGRAMOS" },
		{ value: 53, label:"MILILITRO" },
		{ value: 54, label:"MILLARES" },
		{ value: 55, label:"MILIMETRO" },
		{ value: 56, label:"MILIMETRO CUADRADO" },
		{ value: 57, label:"MILIMETRO CUBICO" },
		{ value: 58, label:"MUESTRAS" },
		{ value: 59, label:"MEGAWATT HORA" },
		{ value: 60, label:"ONZAS" },
		{ value: 61, label:"PAILAS" },
		{ value: 62, label:"PALETAS" },
		{ value: 63, label:"PAQUETE" },
		{ value: 64, label:"PLACAS" },
		{ value: 65, label:"PLANCHAS" },
		{ value: 66, label:"PLIEGO" },
		{ value: 67, label:"PIES" },
		{ value: 68, label:"PIES CUADRADOS" },
		{ value: 69, label:"PIES CUBICOS" },
		{ value: 70, label:"PIES TABLARES(MADERA)" },
		{ value: 71, label:"PULGADAS" },
		{ value: 72, label:"PIEZAS" },
		{ value: 73, label:"QUINTAL METRICO (100 KG)" },
		{ value: 74, label:"QUINTAL USA (100 LB)" },
		{ value: 75, label:"RAMOS" },
		{ value: 76, label:"RESMA" },
		{ value: 77, label:"ROLLOS" },
		{ value: 78, label:"SACO" },
		{ value: 79, label:"SET" },
		{ value: 80, label:"TAMBOR" },
		{ value: 81, label:"TONELADA CORTA" },
		{ value: 82, label:"TONELADA CORTA SECA" },
		{ value: 83, label:"TIRAS" },
		{ value: 84, label:"TONELADA LARGA" },
		{ value: 85, label:"TONELADA LARGA SECA" },
		{ value: 86, label:"TONELADAS" },
		{ value: 87, label:"TONELADA CUBICA" },
		{ value: 88, label:"TONELADA METRICA SECA" },
		{ value: 89, label:"TUBOS" },
		{ value: 90, label:"UNIDAD" },
		{ value: 91, label:"UNIDAD POR 10**3" },
		{ value: 92, label:"UNIDAD PO 10**6" },
		{ value: 93, label:"CIENTO DE UNIDADES" },
		{ value: 94, label:"MILES DE UNIDADES" },
		{ value: 95, label:"MILLON DE UNIDADES" },
		{ value: 96, label:"YARDA" },
		{ value: 97, label:"YARDA CUADRADA" }
		]
	};
